# Generated by Django 4.1.3 on 2022-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
