# Generated by Django 4.1.3 on 2022-11-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_resposta_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='pergunta',
            new_name='descricao',
        ),
    ]
