# Generated by Django 4.1.3 on 2022-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_rename_pergunta_pergunta_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='titulo',
            field=models.CharField(default='Default title', max_length=80),
        ),
    ]
