# Generated by Django 4.1.3 on 2022-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0005_pergunta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
    ]
